name: Greetings

on:
    push:
        branches:
            - main

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: "greet user"
              run: echo "Hello Jee"
